sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.6
    env: TOXENV=py36
  - python: pypy
    env: TOXENV=pypy

install:
    - pip install tox codecov

script:
    - tox -e $TOXENV

after_success:
    - codecov
